name: guessflag
description: Guess countries flags.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  step_progress_indicator: ^1.0.2
  path_provider: ^2.1.1
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: master
      path: packages/path_provider/path_provider_aurora
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/icons/
    - assets/countries.json
    - assets/countries_test.json